AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main template to deploy AWS infrastructure with VPC, subnets, route tables, security groups, and EC2 instances'

Parameters:
  VpcCIDR:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1CIDR:
    Description: CIDR block for Public Subnet 1
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnet1CIDR:
    Description: CIDR block for Private Subnet 1
    Type: String
    Default: 10.0.2.0/24

  AvailabilityZone:
    Description: Availability Zone for subnets
    Type: AWS::EC2::AvailabilityZone::Name

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access
    Type: AWS::EC2::KeyPair::KeyName

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium

  SSHLocation:
    Description: IP address range allowed for SSH access (in CIDR notation)
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

  BucketName:
    Description: S3 bucket name where templates are stored
    Type: String
    Default: lab1-cloudformation-bucket

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.ap-southeast-1.amazonaws.com/modules/vpc.yaml
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        AvailabilityZone: !Ref AvailabilityZone
        SSHLocation: !Ref SSHLocation
      TimeoutInMinutes: 20

  # Route Tables Stack
  RouteTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.ap-southeast-1.amazonaws.com/modules/route-tables.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId
      TimeoutInMinutes: 20

  # Security Groups Stack
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.ap-southeast-1.amazonaws.com/modules/security-groups.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        SSHLocation: !Ref SSHLocation
      TimeoutInMinutes: 10

  # EC2 Instances Stack
  EC2InstancesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [SecurityGroupsStack, RouteTablesStack]
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3.ap-southeast-1.amazonaws.com/modules/ec2-instance.yaml
      Parameters:
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PublicSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.PublicEC2SecurityGroupId
        PrivateSecurityGroupId: !GetAtt SecurityGroupsStack.Outputs.PrivateEC2SecurityGroupId
        KeyName: !Ref KeyName
        InstanceType: !Ref InstanceType
      TimeoutInMinutes: 15

Outputs:
  VPCId:
    Description: VPC ID
    Value: !GetAtt VPCStack.Outputs.VpcId

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !GetAtt VPCStack.Outputs.InternetGatewayId

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !GetAtt VPCStack.Outputs.PublicSubnet1Id

  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !GetAtt VPCStack.Outputs.PrivateSubnet1Id

  NATGatewayId:
    Description: NAT Gateway ID
    Value: !GetAtt RouteTablesStack.Outputs.NatGatewayId

  PublicEC2IP:
    Description: Public IP of EC2 instance in public subnet
    Value: !GetAtt EC2InstancesStack.Outputs.PublicEC2InstancePublicIP

  PrivateEC2IP:
    Description: Private IP of EC2 instance in private subnet
    Value: !GetAtt EC2InstancesStack.Outputs.PrivateEC2InstancePrivateIP
