AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC with Public and Private Subnets for AWS Infrastructure'

Parameters:
  VpcCIDR:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16

  PublicSubnet1CIDR:
    Description: CIDR block for Public Subnet 1
    Type: String
    Default: 10.0.1.0/24

  PrivateSubnet1CIDR:
    Description: CIDR block for Private Subnet 1
    Type: String
    Default: 10.0.2.0/24

  AvailabilityZone:
    Description: Availability Zone for subnets
    Type: AWS::EC2::AvailabilityZone::Name

  SSHLocation:
    Description: IP address range allowed for SSH access (in CIDR notation)
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

Resources:
  # VPC Creation
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

  # Public Subnet - accessible from the internet
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref PublicSubnet1CIDR
      MapPublicIpOnLaunch: true  # Auto-assign public IP to instances in this subnet
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-public-subnet-1

  # Private Subnet - no direct internet access
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref PrivateSubnet1CIDR
      MapPublicIpOnLaunch: false  # No public IP for instances in this subnet
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-private-subnet-1

  # Internet Gateway - allows communication between VPC and internet
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-igw

  # Attach Internet Gateway to the VPC
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Default Security Group for the VPC
  DefaultSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Default Security Group for VPC
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref SSHLocation  # Use parameter instead of hardcoded value
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-default-sg

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC

  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Value: !Ref PublicSubnet1

  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Value: !Ref PrivateSubnet1

  InternetGatewayId:
    Description: Internet Gateway ID
    Value: !Ref InternetGateway

  DefaultSecurityGroupId:
    Description: Default Security Group ID
    Value: !Ref DefaultSecurityGroup
